# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  import subprocess,os,math


# data=subprocess.check_output(['netsh', 'wlan','show','profiles']).decode('utf-8')
# data = subprocess.check_output(['netsh','wlan','show','profiles']).decode(get_encoding).split('\n')

data = subprocess.check_output(['netsh','wlan','show','profiles']).decode('latin1').split("\n")
wifi=[i.split(":")[1][1:-1]for i in data if "All User Profile" in i]
for i in wifi:
	result=subprocess.check_output(['netsh','wlan','show','profile',i,'key=clear']).decode('latin1').split("\n")
	result=[i.split(":")[1][1:-1]for i in result if "Key Content" in i]
	password="".join(result)
	print(f"{i}: {password}")
# isse bachne ke liye ap apna wifi ,hotstop ka name  (kãyêl Ãßçêô) aise special character use kr skte hn
['netsh', 'wlan', 'show', 'profile', '\x80ool', 'key=clear']

# inthis case it not read characters

n = int(input())
temp = list(map(int, input().split(' ')[:n]))
for j in range(len(temp)-1,-1,-1):
    print(temp[j])

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
